### ISSUE TITLE
Add support to include Doxygen tags \code and \endcode

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [dronecore/DroneCore#259]
To improve including code snippets in docs, it is most suitable to use Doxygen tags: [\code](http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdcode) & [\endcode](http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdendcode).

Added PR which use these Doxygen tags: ([dronecore/DroneCore/#258](https://github.com/dronecore/DroneCore/pull/258)).

```
$ ./generate_docs.sh
......
Generating: /home/shakthi/karma/fork/DroneCore/install/docs/xml/classdronecore_1_1_follow_me.xml (class xml)
Unhanded tag in markdown_any_tag: programlisting
Traceback (most recent call last):
  File "/home/shakthi/karma/fork/DroneCore/generate_markdown_from_doxygen_xml.py", line 1074, in <module>
    markdown_string=currentClass.markdown()
  File "/home/shakthi/karma/fork/DroneCore/generate_markdown_from_doxygen_xml.py", line 957, in markdown
    outputstring+=the_function.markdown()
  File "/home/shakthi/karma/fork/DroneCore/generate_markdown_from_doxygen_xml.py", line 683, in markdown
    functionstring+='\n\n%s' % markdown_any_tag(self.detaileddescription).strip()
  File "/home/shakthi/karma/fork/DroneCore/generate_markdown_from_doxygen_xml.py", line 117, in markdown_any_tag
    child_text += markdown_any_tag(child,html=html,para=para) #.strip()
  File "/home/shakthi/karma/fork/DroneCore/generate_markdown_from_doxygen_xml.py", line 122, in markdown_any_tag
    child_text+=str(ET.tostring(child),'utf-8')
TypeError: str() takes at most 1 argument (2 given)
```

**Comment by hamishwillee** [comment]
Implemented/discussed in #258
